### ISSUE TITLE
Want to make this mobile responsive.

### ISSUE THREAD

**Issue by sunami09** [sunami09/my-portfolio#1]
![WhatsApp Image 2023-02-05 at 12 42 26 PM](https://user-images.githubusercontent.com/66564001/216844742-a4cc9f9c-45bd-41a3-9768-3cbbb87d8aaf.jpeg)

**Comment by fatemaker254** [comment]
Hi @sunami09  Pls assign me to this issue.

**Comment by sunami09** [comment]
Solved
